services:
  - type: web
    name: goonio
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    initialDelaySeconds: 45
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: UV_VERSION
        value: 0.2.14
